# Configuração do banco de dados usando variáveis de ambiente
spring.datasource.url=jdbc:mysql://localhost:3306/casafilmes
spring.datasource.username=root
spring.datasource.password=#cart3ir4el0k4..,

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=Always